# Generated by Django 4.1 on 2022-08-20 11:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News_data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unique_id", models.CharField(max_length=100, null=True)),
                ("heading", models.CharField(max_length=400, null=True)),
                ("img", models.URLField(max_length=300)),
                ("url", models.URLField(max_length=300)),
                (
                    "date",
                    models.DateTimeField(
                        verbose_name=datetime.datetime(
                            2022,
                            8,
                            20,
                            11,
                            36,
                            13,
                            607374,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
            ],
        ),
    ]
