# Generated by Django 4.1 on 2022-08-20 12:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news_data",
            name="date",
            field=models.DateTimeField(
                verbose_name=datetime.datetime(
                    2022, 8, 20, 12, 55, 16, 958864, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
