# Generated by Django 4.1 on 2022-08-20 13:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_news_data_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="news_data",
            name="unique_id",
        ),
        migrations.AlterField(
            model_name="news_data",
            name="date",
            field=models.DateTimeField(
                verbose_name=datetime.datetime(
                    2022, 8, 20, 13, 15, 43, 694755, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
