# Generated by Django 4.1 on 2022-08-20 17:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_news_data_content_alter_news_data_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news_data",
            name="content",
            field=models.CharField(default="failed to load data", max_length=5000),
        ),
        migrations.AlterField(
            model_name="news_data",
            name="date",
            field=models.DateTimeField(
                null=True,
                verbose_name=datetime.datetime(
                    2022, 8, 20, 17, 44, 42, 147426, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
    ]
