# Generated by Django 4.1 on 2022-08-21 06:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_news_data_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news_data",
            name="date",
            field=models.DateTimeField(
                null=True,
                verbose_name=datetime.datetime(
                    2022, 8, 21, 6, 14, 34, 993106, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
    ]
