# Generated by Django 4.1 on 2022-09-08 15:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_alter_news_data_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="news_data",
            name="category",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="news_data",
            name="date",
            field=models.DateTimeField(
                null=True,
                verbose_name=datetime.datetime(
                    2022, 9, 8, 15, 28, 18, 696044, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AlterField(
            model_name="news_data",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
