# Generated by Django 4.1 on 2022-09-14 18:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_alter_news_data_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news_data",
            name="date",
            field=models.DateTimeField(
                null=True,
                verbose_name=datetime.datetime(
                    2022, 9, 14, 18, 18, 39, 618971, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
    ]
